@startuml
skinparam monochrome true
skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam classFontSize 14
skinparam classAttributeFontSize 12
title Диаграмма деятельности: Сортировка и фильтрация данных

|Трейдер|
start
:Перейти на дашборд с рыночными данными;
|Система|
:Загрузить текущие данные\nпо всем торговым парам;
:Отобразить таблицу с данными\n(доходность, объем, ставка финансирования);
|Трейдер|
:Просмотреть таблицу с торговыми парами;



|Трейдер|
:Выбрать параметр сортировки\n(доходность/APY, объем торгов,\nставка финансирования);

|Система|
if (Параметр сортировки выбран?) then (Да)
  :Определить направление сортировки\n(по возрастанию/убыванию);
endif
:Отсортировать данные по выбранному параметру;
:Обновить отображение таблицы;

|Трейдер|
:Нажать кнопку "Фильтры";

|Система|
:Отобразить панель фильтров;
:Показать доступные параметры фильтрации;

|Трейдер|
repeat :Выбрать торговые пары для фильтрации;
|Система|
:Проверить доступность выбранных пар;
backward :Предупреждение\n"Некоторые пары недоступны";
repeat while (Все пары доступны?) is (Нет) not (Да)

|Трейдер|
:Установить минимальный порог доходности;
:Установить минимальный объем торгов;
:Выбрать диапазон ставок финансирования;

|Система|
if (Фильтры применены?) then (Да)
  :Применить выбранные фильтры к данным;
endif
:Отфильтровать данные по критериям;
:Обновить отображение таблицы;

|Трейдер|
:Оценить отфильтрованные и отсортированные данные;
if (Нужно изменить параметры?) then (Да)
  :Выбрать параметр сортировки\n(доходность/APY, объем торгов,\nставка финансирования);
endif

|Система|
if (Пользователь сохраняет настройки?) then (Да)
  :Сохранить текущие настройки фильтров\nи сортировки в профиле пользователя;
endif

|Трейдер|
:Закрыть панель фильтров;
:Продолжить работу с данными;

stop

@enduml