@startuml
skinparam monochrome true
skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam classFontSize 14
skinparam classAttributeFontSize 12
title Диаграмма деятельности: Регистрация гостя

|Гость|
start
:Перейти на страницу регистрации;

repeat :Ввести email-адрес;
|Система|
:Проверить формат email;
backward :Предупреждение;
repeat while (Email валиден?) is (Нет) not (Да)


|Гость|
repeat :Ввести пароль;
|Система|
:Проверить сложность;
backward :Предупреждение;
repeat while (Пароль сложный?) is (Нет) not (Да)

|Гость|
repeat :Подтвердить пароль;
|Система|
:Проверить совпадение;
backward :Предупреждение;
repeat while (Пароли совпадают?) is (Нет) not (Да)


|Гость|
:Ознакомиться с условиями использования;
:Поставить галочку "Согласен с условиями";
:Нажать кнопку "Зарегистрироваться";

|Система|
:Проверить, существует ли аккаунт с таким email;
if (Email уже зарегистрирован?) then (да)
  :Показать ошибку "Email уже занят";
  |Гость|
  detach
endif

|Система|
:Создать новую учетную запись\nс временным статусом "неактивен";
:Сгенерировать уникальную ссылку подтверждения;
:Отправить письмо с ссылкой подтверждения\nна указанный email;
:Сохранить настройки по умолчанию\nдля нового пользователя;

|Гость|
:Пройти по ссылке подтверждения\nв полученном email;

|Система|
:Активировать учетную запись;

|Гость|
:Получить сообщение об успешной активации аккаунта;
stop

@enduml